# Generated by Django 3.0.2 on 2020-05-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSiteApp', '0003_auto_20200506_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverPhoto',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
