# Generated by Django 3.0.2 on 2020-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSiteApp', '0004_auto_20200506_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverPhoto',
            field=models.ImageField(default='default.jpg', upload_to='coverphotos'),
        ),
    ]
