# Generated by Django 3.0.2 on 2020-05-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSiteApp', '0005_auto_20200509_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biodata',
            field=models.TextField(default='something', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='www.example.com', max_length=200),
        ),
    ]
