# Generated by Django 3.0.2 on 2020-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSiteApp', '0006_auto_20200510_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='dd/mm/yy', max_length=200),
        ),
    ]
