# Generated by Django 3.0.2 on 2020-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSiteApp', '0009_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(default='default.jpg', upload_to='post_content'),
        ),
    ]
